spring:
  application:
    name: blog-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: xxxxxx
    password: xxxxxx
    url: jdbc:mysql://localhost:3306/tim?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8099